export enum ActionType {
  SAVE_INTERACTION = "SAVE_INTERACTION",
  AI_STARTED = "AI_STARTED",
  AI_COMPLETED = "AI_COMPLETED",
  MIRROR_SENT = "MIRROR_SENT",
  DISCORD_REPLY_SENT = "DISCORD_REPLY_SENT",
  RETRY = "RETRY",
  FAILURE = "FAILURE"
}
